In [16]:
!pip install numpy

In [13]:
import numpy as np

In [12]:
a = np.array([])

In [14]:
a

array([], dtype=float64)

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[0]

1

In [22]:
arr[-1]

10

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [25]:
a[1]

array([5, 6, 7, 8])

In [26]:
a[0]

array([1, 2, 3, 4])

In [27]:
a.shape

(3, 4)

In [28]:
a.ndim

2

In [29]:
a = np.arange(6).reshape(6,1)

In [30]:
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [34]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
a = a.reshape(2,3)

In [38]:
np.reshape(a, (6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [39]:
a = np.array([1, 2, 3, 4, 5, 6])

In [40]:
a.shape

(6,)

In [41]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [43]:
a3 = a2[np.newaxis]
print(a3.shape)
print(a3)

(1, 1, 6)
[[[1 2 3 4 5 6]]]


In [47]:
row_vector = a[np.newaxis, :]
print(a)
print(row_vector.shape)
print(row_vector)

[1 2 3 4 5 6]
(1, 6)
[[1 2 3 4 5 6]]


In [48]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [49]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [50]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [51]:
data = np.arange(16)
print(data)
print(data[0::3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  3  6  9 12 15]


In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
seven_to_nine_filter = ((a > 7) & (a<= 9))
a[seven_to_nine_filter]

array([8, 9])

In [61]:
a[( (a>=7) & (a<=9))]

array([7, 8, 9])

In [62]:
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [63]:
divisible_by_2.reshape(3,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [64]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [65]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr1 = [3,8]

In [70]:
a_1 = np.array([[1, 1],
               [2, 2]])

In [72]:
a_2 = np.array([[3, 3],
               [4, 4]])

In [76]:
np.vstack( (a_1, a_2) )

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [77]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [78]:
np.hstack((a_2, a_1))

array([[3, 3, 1, 1],
       [4, 4, 2, 2]])

In [79]:
np.hstack( (a_2, a_2, a_1) )

array([[3, 3, 3, 3, 1, 1],
       [4, 4, 4, 4, 2, 2]])

In [80]:
np.hstack( (a_2, a_1, a_2, a_1))

array([[3, 3, 1, 1, 3, 3, 1, 1],
       [4, 4, 2, 2, 4, 4, 2, 2]])

In [81]:
arrsplit = np.arange(1, 25).reshape(2, 12)

In [82]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [83]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [86]:
np.split(arrsplit, 2, axis=1)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [87]:
splitted_arr = np.split(arrsplit, 2, axis=1)
splitted_arr

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [89]:
splitted_arr[1]

array([[ 7,  8,  9, 10, 11, 12],
       [19, 20, 21, 22, 23, 24]])

In [90]:
splitted_arr = np.split(arrsplit, 2, axis=1)
splitted_arr

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [92]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
c = a.copy()

In [96]:
c 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
c[2][1]=1000

In [99]:
c

array([[   1,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9, 1000,   11,   12]])

In [100]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [102]:
print(a+a)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [103]:
a -a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [106]:
a * a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [107]:
a/a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
a.sum()

78

In [114]:
b = np.array([[1, 2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [115]:
b.sum()

10

In [116]:
b.sum(axis=0)

array([4, 6])

In [117]:
b.sum(axis=1)

array([3, 7])

In [118]:
data = np.array([1, 2])
data

array([1, 2])

In [120]:
ones = np.ones(2)
ones

array([1., 1.])

In [121]:
data+ones

array([2., 3.])

In [122]:
data - ones

array([0., 1.])

In [123]:
data/ones

array([1., 2.])

In [124]:
data.shape

(2,)

In [125]:
data*2.6

array([2.6, 5.2])

In [126]:
data*1.6

array([1.6, 3.2])

In [127]:
ones*10

array([10., 10.])

In [129]:
np.random.randint(4, 11, 20)

array([ 5,  8, 10,  5,  7,  4,  8, 10,  8,  7,  5,  5, 10,  6,  8,  4, 10,
        9,  5,  8])

In [130]:
7

array([1, 2])